# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PARKinetics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PARKinetics

  target 'PARKineticsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PARKineticsUITests' do
    # Pods for testing
  end

end

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Database'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

pod 'Charts'
